name = "jh-adapter-backend-cloudflare"
main = "backend-cloudflare/src/worker.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "jihu-api"
database_id = "e8d34f1a-a2df-48a9-9f29-62f9e96e1ead"

